version: '3'
services:
  web:
    container_name: asesorias-iudigital
    restart: always
    build: .
    ports:
      - "5000:3000"
    volumes:
      - .:/usr/src/app

  proyectos:
    container_name: asesorias-iudigital-proyectos
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.proyectos
    ports:
      - "5001:3000"
    volumes:
      - .:/usr/src/app

  nginx:
    container_name: asesorias-iudigital-nginx
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  jenkins:
    container_name: jenkins
    restart: always
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  jenkins_data:
